feat/receipt-generation
taronaeo/IT2555-ASP pull request #17
Opened 2023-06-13 14:49 UTC by deziiii

2023-07-29 18:10 UTC, taronaeo commented on src/lib/models/metadata.ts
1. Remove the unused import
2. Model can be merged together with the `receipt.ts` file since it's not being used anywhere else.
3. No need for `itemId` since they are not registering their product catalogue with us - just have `itemName`, `price`, and maybe more fields to indicate if the item has been adjusted specifically for discount, or has been remarked in any way, e.g., damaged goods, or sold at sale

2023-07-29 18:10 UTC, taronaeo commented on src/lib/models/item.ts
1. Remove the unused import
2. Model can be merged together with the receipt.ts file since it's not being used anywhere else.
3. No need for itemId since they are not registering their product catalogue with us - just have itemName, price, and maybe more fields to indicate if the item has been adjusted specifically for discount, or has been remarked in any way, e.g., damaged goods, or sold at sale

2023-07-29 18:14 UTC, taronaeo commented on src/lib/models/receipt.ts
1. Not everything should be classified as `readonly`. Think mutations.
2. `userUid` can be null as well if the receipt has not been assigned to a user.
3. `date` MUST be using Firestore's `FieldValue` type. This must be enforced. Insertions will use `FieldValue.serverTimestamp()` function to have the server generate the accurate date and time
4. `time` can be merged together with `date`. Infact, call it `createdAt`, the same convention as in `User` model.
5. Remove unused imports
6.

2023-07-29 18:15 UTC, taronaeo commented on src/lib/models/user.ts
1. Create a model specifically for the API keys.
2. `apiKeys` doesn't need to be strictly `null` type. You can have empty array `[]` and it would serve the same purpose.

2023-07-29 18:17 UTC, taronaeo commented on src/lib/models/user.ts
`vendorId`, `vendorName`, `apiKeys` might be better off in their own `vendors` collection, with a field referencing the ownership back to the user. clumping everything here might get a little hectic after a while

2023-07-29 18:17 UTC, taronaeo commented on src/routes/(app)/bmw/+page.svelte
This is test code. Test code should NEVER be committed, or released to master branch. Please remove

2023-07-29 18:19 UTC, taronaeo commented on src/routes/(app)/branch-creation/+page.svelte
Fatal error

```js
+page.svelte:48 Uncaught (in promise) FirebaseError: Invalid document reference. Document references must have an even number of segments, but users has 1.
```

Also, remove commented test code prior to committing for pull request - secure coding.

2023-07-29 18:21 UTC, taronaeo commented on src/routes/(app)/receipt/[receipt_id]/+page.svelte
> +    }).catch(err => console.log("Error occured"))
Insecure code. Will get us penalised for writing this way. This code should have been implemented in Firestore Rules and not the client side.

2023-07-29 18:22 UTC, taronaeo commented on src/routes/(app)/receipt/[receipt_id]/+page.svelte
Design looks good generally. But I'm able to view the receipt `Zo31Tn6GLyg7MciONVsS` even after it had been assigned to a user.

2023-07-29 18:23 UTC, taronaeo commented on src/routes/(epos)/new-epos/+page.svelte
> +    }
Please do not put all your code into one reactive declaration. It works but will introduce a lot of bugs in the future. Refactor it while you can

2023-07-29 18:25 UTC, taronaeo commented on src/routes/(epos)/receipt-test/+page.svelte
Test code should NEVER be committed to a pull request.

Also, you have a fatal error
```js
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'uid')
    at instance (http://localhost:3000/src/routes/(epos)/receipt-test/+page.svelte:139:25)
    at init (index.mjs:2165:11)
    at new Page (http://localhost:3000/src/routes/(epos)/receipt-test/+page.svelte:180:3)
    at createProxiedComponent (svelte-hooks.js?v=fef75ea0:341:9)
    at new ProxyComponent (proxy.js?v=fef75ea0:242:7)
    at new Proxy<+page> (proxy.js?v=fef75ea0:349:11)
    at construct_svelte_component_dev (index.mjs:2398:26)
    at Array.create_else_block (root.svelte:48:83)
    at Array.create_default_slot (root.svelte:43:22)
    at create_slot (index.mjs:71:28)
```

2023-07-29 18:27 UTC, taronaeo commented on src/routes/api/epos-upload/+server.ts
This is the code for generating the receipt into `receipts` collection right? It should be replaced into the Cloud Functions folder to ensure Firestore Admin access.

You're now able to do this because Firestore Rules have not been enforced yet. Once this kicks in, your API will fail

2023-07-29 18:27 UTC, taronaeo requested changes
Review and refactor following comments

2023-07-31 18:44 UTC, deziiii commented on src/lib/models/item.ts
1) unused import removed
2) model merged
3) itemId removed

2023-08-01 12:11 UTC, taronaeo approved these changes

2023-08-01 12:11 UTC, merged