Feat/fixes to eposnreceipt
taronaeo/IT2555-ASP pull request #26
Opened 2023-08-05 15:49 UTC by deziiii

2023-08-05 19:13 UTC, taronaeo commented on functions/src/http/onHttpReceiptSubmit.ts
sehr gut! very clear commit messages and good coding practices.

2023-08-05 19:14 UTC, taronaeo commented on src/routes/(app)/branch-creation/+page.svelte
Would highly recommend using svelte-forms-lib and Zod to handle all your validation logic. But good work

2023-08-05 19:26 UTC, taronaeo requested changes
I think your code is generally fine except for that one problem in `src/routes/(epos)/new-epos/+page.svelte`. Re-request approval again once you've updated it

2023-08-05 19:26 UTC, taronaeo commented on src/routes/(epos)/new-epos/+page.svelte
> +        })
woah! watch out. this is computationally expensive.

I would suggest this instead
```js
}).then(res => {
  if (res.status !== 200) throw Error(`API Endpoint returned ${res.status}, with ${res.message}`);
  return res.json();
}
```

this is computationally expensive because in both if clauses, you're converting the result into json(), which is redundant in the case of throwing an error.

With the case of my suggested code above (not tested yet), your thrown error would get caught in the `.catch()` code below. So don't worry.

2023-08-05 19:26 UTC, taronaeo commented on src/routes/(epos)/new-epos/+page.svelte
> +        })
Also, by throwing an error instead of converting to `.json()`, you ensure that it does not continue down the `.then()` chain

2023-08-05 19:26 UTC, taronaeo commented on src/routes/(epos)/new-epos/+page.svelte
> +            validQR = false;
Would suggest adding the `console.error(err)` here if you still need it for logging purposes.

2023-08-05 19:26 UTC, taronaeo commented on src/routes/(epos)/new-epos/+page.svelte
> +        }, 3000)
You might want to rename the variable to `expired` instead of `timeout`. From reading only this code, I thought that `timeout` was used to determine if the API has responded within 3 seconds or not.

2023-08-05 20:35 UTC, deziiii commented on src/routes/(app)/branch-creation/+page.svelte
zod damn cool bro, input validation changed to use zod

2023-08-05 20:37 UTC, deziiii commented on src/routes/(epos)/new-epos/+page.svelte
> +        })
changed to:

``` javascript
.then(res => {
            return res.json();
        })
          .then(data =>{
            if(data.status != 200){
                throw Error(`API Endpoint returned ${data.status}, with ${data.message}`)
            }   
            generateQR(data.message);
            generatedReceipt = data.message;
          }).catch(err => {
            validQR = false;
            console.error(err);
          })
```

2023-08-05 20:37 UTC, deziiii commented on src/routes/(epos)/new-epos/+page.svelte
> +            validQR = false;
added

2023-08-05 20:37 UTC, deziiii commented on src/routes/(epos)/new-epos/+page.svelte
> +        }, 3000)
changed

2023-08-06 05:56 UTC, taronaeo commented on src/routes/(epos)/new-epos/+page.svelte
> +        })
that's a fair approach. but I would still caution you against converting to JSON first before checking the response status code. if your API did not return `status`, your code would fail.

I would still encourage checking it this way as the response object always provides a status code
```js
}).then(res => {
  if (res.status !== 200) throw Error(`API Endpoint returned ${res.status}, with ${res.message}`);
  return res.json();
}
```

let me know how you would like to proceed (change to check response status code first/leave the code be)

2023-08-06 05:58 UTC, taronaeo commented on src/routes/(app)/branch-creation/+page.svelte
> +  let inputCreationPostal: number | undefined = ""
```js
Type 'string' is not assignable to type 'number'.ts(2322)
let inputCreationPostal: number | undefined
No quick fixes available
```

I have more comments below. Wait for it before changing

2023-08-06 06:21 UTC, taronaeo requested changes
More changes

2023-08-06 06:21 UTC, taronaeo commented on src/routes/(app)/branch-creation/+page.svelte
> +  }),
there isn't an actual need for `postalCode` to be a union of `number` and `string`. by convention, identifiers should use string instead of numbers due to formatting.

you should do something like this:
```js
    postalCode: z
      .string({ required_error: 'Postal code is required' })
      .min(6, 'Invalid postal code format')
      .max(6, 'Invalid postal code format')
      .refine(
        (postalCode) => {
          const parsedPostalCode = Number(postalCode);
          if (isNaN(parsedPostalCode)) return false;
          if (parsedPostalCode <= 100000) return false;
          if (parsedPostalCode >= 999999) return false;
          return true;
        },
        {
          message:
            'Invalid postal code. Only valid 6-digital SG postal code is allowed.',
        }
      ),
```

2023-08-06 06:21 UTC, taronaeo commented on src/routes/(app)/branch-creation/+page.svelte
You might want to check if the user is already onboarded, and if they have a valid vendor document. If not, they should be redirected to /onboarding

2023-08-06 08:34 UTC, deziiii commented on src/routes/(app)/branch-creation/+page.svelte
> +  let inputCreationPostal: number | undefined = ""
fixed

2023-08-06 08:34 UTC, deziiii commented on src/routes/(app)/branch-creation/+page.svelte
> +  }),
fixed

2023-08-06 08:34 UTC, deziiii commented on src/routes/(app)/branch-creation/+page.svelte
fixed

2023-08-06 09:31 UTC, taronaeo commented on src/routes/(app)/branch-creation/+page.svelte
you should use `replaceState: true` in `goto()` to prevent users from going back and getting redirected back to `onboarding`. looks good overall

2023-08-06 09:33 UTC, taronaeo approved these changes
LGTM

2023-08-06 10:22 UTC, taronaeo approved these changes
LGTM

2023-08-06 10:23 UTC, merged